# Generated by Django 5.0.6 on 2024-06-12 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("ArtistId", models.AutoField(primary_key=True, serialize=False)),
                ("ArtistName", models.CharField(max_length=100)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("AuthorId", models.AutoField(primary_key=True, serialize=False)),
                ("AuthorName", models.CharField(max_length=100)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryId", models.AutoField(primary_key=True, serialize=False)),
                ("CategoryName", models.CharField(max_length=50)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manga",
            fields=[
                ("MangaId", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=255)),
                ("Description", models.TextField(blank=True)),
                ("PublicationDate", models.DateField(blank=True, null=True)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                ("MangaCreationDate", models.DateField(blank=True, null=True)),
                ("IsFree", models.BooleanField(default=False)),
                (
                    "ArtistId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="AppMangaScape.artist",
                    ),
                ),
                (
                    "AuthorId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="AppMangaScape.author",
                    ),
                ),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Following",
            fields=[
                ("FollowingId", models.AutoField(primary_key=True, serialize=False)),
                ("FollowingDate", models.DateField()),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "MangaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.manga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("CommentId", models.AutoField(primary_key=True, serialize=False)),
                ("Content", models.TextField()),
                ("CommentDate", models.DateTimeField(blank=True, null=True)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "MangaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.manga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("ChapterId", models.AutoField(primary_key=True, serialize=False)),
                ("ChapterNumber", models.IntegerField()),
                ("Title", models.CharField(blank=True, max_length=255)),
                ("PublicationDate", models.DateField(blank=True, null=True)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "MangaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.manga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MangaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CategoryId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.category",
                    ),
                ),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_category_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "MangaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.manga",
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_category_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("NotificationId", models.AutoField(primary_key=True, serialize=False)),
                ("Message", models.CharField(max_length=255)),
                ("ReadNotification", models.BooleanField(default=False)),
                ("NotificationDate", models.DateTimeField(blank=True, null=True)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "FollowingId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.following",
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("PageId", models.AutoField(primary_key=True, serialize=False)),
                ("PageNumber", models.IntegerField()),
                ("PageImagePath", models.CharField(max_length=255)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                ("ReadingDate", models.DateField(blank=True, null=True)),
                (
                    "ChapterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.chapter",
                    ),
                ),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("PermissionId", models.AutoField(primary_key=True, serialize=False)),
                ("PermissionName", models.CharField(max_length=50)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("RatingId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("RatingDate", models.DateTimeField(blank=True, null=True)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "MangaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.manga",
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                ("ReadingId", models.AutoField(primary_key=True, serialize=False)),
                ("PageNumber", models.IntegerField()),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("in progress", "in progress"),
                            ("completed", "completed"),
                        ],
                        default="in progress",
                        max_length=20,
                    ),
                ),
                ("ReadingDate", models.DateField()),
                ("ReadingTime", models.TimeField()),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "ChapterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.chapter",
                    ),
                ),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("RoleId", models.AutoField(primary_key=True, serialize=False)),
                ("RoleName", models.CharField(max_length=50)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permission_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permission_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "PermissionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.permission",
                    ),
                ),
                (
                    "RoleId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("StateId", models.AutoField(primary_key=True, serialize=False)),
                ("StateName", models.CharField(max_length=50)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manga",
            name="StateId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AppMangaScape.state",
            ),
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                ("UploadId", models.AutoField(primary_key=True, serialize=False)),
                ("UploadDate", models.DateTimeField(blank=True, null=True)),
                ("RecordCreationDate", models.DateTimeField(auto_now_add=True)),
                ("RecordModificationDate", models.DateTimeField(blank=True, null=True)),
                (
                    "CreatedByUserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "MangaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppMangaScape.manga",
                    ),
                ),
                (
                    "ModifiedByUserId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="mangacategory",
            constraint=models.UniqueConstraint(
                fields=("MangaId", "CategoryId"), name="unique_manga_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("RoleId", "PermissionId"), name="unique_role_permission"
            ),
        ),
    ]
