# Generated by Django 5.0.6 on 2024-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppMangaScape", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manga",
            name="ArtistId",
        ),
        migrations.RemoveField(
            model_name="manga",
            name="AuthorId",
        ),
        migrations.AddField(
            model_name="manga",
            name="ArtistId",
            field=models.ManyToManyField(
                blank=True, related_name="mangas", to="AppMangaScape.artist"
            ),
        ),
        migrations.AddField(
            model_name="manga",
            name="AuthorId",
            field=models.ManyToManyField(
                blank=True, related_name="mangas", to="AppMangaScape.author"
            ),
        ),
    ]
