# Generated by Django 5.0.6 on 2024-07-02 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppMangaScape", "0002_remove_manga_artistid_remove_manga_authorid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manga",
            name="ArtistId",
        ),
        migrations.RemoveField(
            model_name="manga",
            name="AuthorId",
        ),
        migrations.AddField(
            model_name="manga",
            name="ArtistId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AppMangaScape.artist",
            ),
        ),
        migrations.AddField(
            model_name="manga",
            name="AuthorId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="AppMangaScape.author",
            ),
        ),
    ]
