# Generated by Django 5.0.6 on 2024-07-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppMangaScape", "0003_remove_manga_artistid_remove_manga_authorid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manga",
            name="ArtistId",
        ),
        migrations.RemoveField(
            model_name="manga",
            name="AuthorId",
        ),
        migrations.AddField(
            model_name="manga",
            name="Artists",
            field=models.ManyToManyField(
                blank=True, related_name="mangas", to="AppMangaScape.artist"
            ),
        ),
        migrations.AddField(
            model_name="manga",
            name="Authors",
            field=models.ManyToManyField(
                blank=True, related_name="mangas", to="AppMangaScape.author"
            ),
        ),
    ]
