# Generated by Django 5.0.6 on 2024-07-02 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppMangaScape", "0005_manga_webpublicationdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manga",
            name="WebPublicationDate",
        ),
    ]
