# Generated by Django 5.0.6 on 2024-07-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppMangaScape", "0006_remove_manga_webpublicationdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="PageImagePath",
        ),
        migrations.AddField(
            model_name="page",
            name="PageImage",
            field=models.ImageField(null=True, upload_to="pages"),
        ),
    ]
